// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class AllTestsTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void test1_age25_ex3_ac0()
    {
        driver.Navigate().GoToUrl("http://localhost/prog2070a03/");
        driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Aman");
        driver.FindElement(By.Id("lastName")).SendKeys("Shabhai");
        driver.FindElement(By.Id("address")).SendKeys("15 Pretoria Road");
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("Cambridge");
        driver.FindElement(By.Id("postalCode")).SendKeys("N1R 5C3");
        driver.FindElement(By.Id("phone")).SendKeys("226-201-2604");
        driver.FindElement(By.Id("email")).SendKeys("Ashabhai5111@conestogac.on.ca");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$2500"));
        }
    }
    [Test]
    public void test2_age25_ex3_ac4()
    {
        driver.Navigate().GoToUrl("http://localhost/prog2070a03/");
        driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Aman");
        driver.FindElement(By.Id("lastName")).SendKeys("Shabhai");
        driver.FindElement(By.Id("address")).SendKeys("15 Pretoria road");
        driver.FindElement(By.Id("city")).SendKeys("Cambridge");
        driver.FindElement(By.Id("postalCode")).SendKeys("N1R 5C3");
        driver.FindElement(By.Id("phone")).SendKeys("226-201-2604");
        driver.FindElement(By.Id("email")).SendKeys("Ashabhai5111@conestogac.on.ca");
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("4");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
        }
    }
    [Test]
    public void test3_age35_ex10_ac2()
    {
        driver.Navigate().GoToUrl("http://localhost/prog2070a03/");
        driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Aman");
        driver.FindElement(By.Id("lastName")).SendKeys("Shabhai");
        driver.FindElement(By.Id("address")).SendKeys("15 Pretoria road");
        driver.FindElement(By.Id("city")).SendKeys("Cambridge");
        driver.FindElement(By.Id("postalCode")).SendKeys("N1R 5C3");
        driver.FindElement(By.Id("phone")).SendKeys("226-201-2604");
        driver.FindElement(By.Id("email")).SendKeys("Ashabhai5111@conestogac.on.ca");
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).SendKeys("10");
        driver.FindElement(By.Id("accidents")).SendKeys("2");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$1350"));
        }
    }
    [Test]
    public void test4_InvalidPhoneNumber()
    {
        driver.Navigate().GoToUrl("http://localhost/prog2070a03/");
        driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Aman");
        driver.FindElement(By.Id("lastName")).SendKeys("Shabhai");
        driver.FindElement(By.Id("address")).SendKeys("15 Pretoria Road");
        driver.FindElement(By.Id("city")).SendKeys("Cambridge");
        driver.FindElement(By.Id("postalCode")).SendKeys("N1R 5C3");
        driver.FindElement(By.Id("phone")).SendKeys("2262012604");
        driver.FindElement(By.Id("email")).SendKeys("Ashabhai5111@conestogac.on.ca");
        driver.FindElement(By.Id("age")).SendKeys("27");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("phone-error")).Text, Is.EqualTo("Phone Number must follow the patterns 111-111-1111 or (111)111-1111"));
    }
    [Test]
    public void test5_InvalidEmail()
    {
        driver.Navigate().GoToUrl("http://localhost/prog2070a03/");
        driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Aman");
        driver.FindElement(By.Id("lastName")).SendKeys("Shabhai");
        driver.FindElement(By.Id("address")).SendKeys("15 Pretoria road");
        driver.FindElement(By.Id("city")).SendKeys("Cambridge");
        driver.FindElement(By.Id("postalCode")).SendKeys("N1R 5C3");
        driver.FindElement(By.Id("phone")).SendKeys("2262012604");
        driver.FindElement(By.Id("email")).SendKeys("Ashabhai5111conestogac.on.ca");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("226-201-2604");
        driver.FindElement(By.Id("email")).SendKeys("Ashabhai5111conestogac.on.ca");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("28");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("email-error")).Text, Is.EqualTo("Must be a valid email address"));
    }
    [Test]
    public void test6_InvalidPostalCode()
    {
        driver.Navigate().GoToUrl("http://localhost/prog2070a03/");
        driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Aman");
        driver.FindElement(By.Id("lastName")).SendKeys("Shabhai");
        driver.FindElement(By.Id("address")).SendKeys("15 Pretoria road");
        driver.FindElement(By.Id("city")).SendKeys("Cambrideh");
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("Cambridge");
        driver.FindElement(By.Id("postalCode")).SendKeys("N1R 533");
        driver.FindElement(By.Id("phone")).SendKeys("226-201-2604");
        driver.FindElement(By.Id("email")).SendKeys("Ashabhai5111@conestogac.on.ca");
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).SendKeys("17");
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        Assert.That(driver.FindElement(By.Id("postalCode-error")).Text, Is.EqualTo("Postal Code must follow the pattern A1A 1A1"));
    }


}
